nelmio_api_doc:
    documentation:
        info:
            title: Сервис авторизации
            description: Это сервис авторизации и управления пользователями.
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$) 
