security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: 'App\Entity\User'
                property: 'username'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin 
            provider: app_user_provider
            form_login:
                login_path: admin_auth_login
                check_path: admin_auth_check
                default_target_path: admin_users_index
                always_use_default_target_path: true
            logout:
                path: admin_auth_logout
                target: admin_auth_login
        api:
            pattern: ^/api 
            jwt: ~
            stateless: true
        main:
            lazy: true
            provider: app_user_provider

    access_control:
        - { path: ^/admin/auth, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
