services:
  app:
    build:
      context: .
      target: frankenphp_prod
    ports:
      - "8080:2015"
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      APP_RUNTIME: Runtime\FrankenPhpSymfony\Runtime
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=16&charset=utf8
      MERCURE_TRANSPORT_URL: ${MERCURE_TRANSPORT_URL:-bolt:///data/mercure.db}
    volumes:
      - .:/app:rw
      - ./frankenphp/conf.d/:/usr/local/etc/php/conf.d/:ro
      - php_sessions:/tmp/sessions
      - php_data:/data
    depends_on:
      - database
    restart: unless-stopped
    networks:
      - app-network

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - app-network
    restart: unless-stopped

volumes:
  database_data:
  php_sessions:
  php_data:

networks:
  app-network:
    driver: bridge