controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

admin_auth_logout:
    path: /admin/auth/logout

admin_auth_check:
    path: /admin/auth/check

api_login_check:
    path: /api/login_check

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }