parameters:

services:
    _defaults:
        autowire: true  
        autoconfigure: true 

    App\:
        resource: '../src/'

    App\EventListener\AdminRedirectListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }